### ISSUE TITLE
Some S3 URLs stopped working

### ISSUE THREAD

**Issue by tilo** [guinslym/Uifaces#2]
e.g. https://s3.amazonaws.com/uifaces/faces/twitter/soffes/128.jpg
does not show up anymore

<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>1124B5E779B958A8</RequestId><HostId>dwtMvRlcTPuCyNxU/NVm5z5I6CPtakNofX16xJ3BRuFR9Ll32dLK4KioHPbqxwo9I5md/S0xYl0=</HostId></Error>

**Comment by tanwangzugata** [comment]
this should be closed -
 fixed in this commit: https://github.com/guinslym/Uifaces/commit/2ed334413177bf14a8c43dc0299396c7d8a264d1

@guinslym could you tag this for release?

**Comment by guinslym** [comment]
hi @tanwangzugata thanks for the comment! I just published the new release on rubygems.
